# Generated by Django 4.2.3 on 2023-08-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.SlugField(max_length=15)),
                ('emp_fname', models.CharField(max_length=50)),
                ('emp_lname', models.CharField(max_length=50)),
                ('emp_gender', models.CharField(max_length=20)),
                ('emp_dob', models.DateField()),
                ('emp_manager', models.CharField(max_length=50)),
                ('emp_contact', models.IntegerField()),
                ('emp_city', models.CharField(max_length=50)),
                ('acc_no', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
                ('contact_person_name', models.CharField(max_length=50)),
                ('contact_person_relation', models.CharField(max_length=50)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_of', to='employeeApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=20)),
                ('role_level', models.CharField(max_length=20)),
                ('role_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_status', models.CharField(blank=True, max_length=20, null=True)),
                ('ticket_amount', models.IntegerField()),
                ('ticket_reason', models.CharField(max_length=200)),
                ('date_raised', models.DateField()),
                ('date_passed', models.DateField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_for', to='employeeApp.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_of', to='employeeApp.role'),
        ),
    ]
