# Generated by Django 4.2.4 on 2023-09-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0003_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='emp_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
