# Generated by Django 4.2.4 on 2023-10-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0008_leaves_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='approver',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logtiming',
            name='approver',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
